intouch_app/models.py
from intouch_app.extensions import db
from sqlalchemy.orm import backref
from flask_login import UserMixin


class Contact(db.Model):
    """Contact model."""

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    email = db.Column(db.String(80))
    phone = db.Column(db.String(20))
    address = db.Column(db.String(200))
    birthday = db.Column(db.Date)
    image_url = db.Column(db.String(400))
    relationship = db.Column(db.String(80))
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    def __str__(self):
        return f"<Contact: {self.name}>"

    def __repr__(self):
        return f"<Contact: {self.name}>"


class Note(db.Model):
    """Contact model."""

    id = db.Column(db.Integer, primary_key=True)
    note = db.Column(db.String(800), nullable=False)
    created_on = db.Column(db.Date)
    contact_id = db.Column(db.Integer, db.ForeignKey("contact.id"), nullable=False)

    def __str__(self):
        return f"<Contact: {self.name}>"

    def __repr__(self):
        return f"<Contact: {self.name}>"


class User(UserMixin, db.Model):
    """User model."""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f"<User: {self.username}>"

intouch_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length


class ContactForm(FlaskForm):
    """Form to create a contact."""

    name = StringField("Name", validators=[DataRequired(), Length(min=3, max=80)])
    email = StringField("Email")
    phone = StringField("Phone")
    address = StringField("Address")
    birthday = DateField("Birthday")
    image_url = StringField("Image URL")
    relationship = StringField("Relationship")
    submit = SubmitField("Save")


class NoteForm(FlaskForm):
    """Form to create a note."""

    note = TextAreaField(
        "Note", validators=[DataRequired(), Length(min=3, max=800)]
    )
    submit = SubmitField("Save")

class DeleteForm(FlaskForm):
    """Form to delete a contact or note."""

    submit = SubmitField("Delete")

intouch_app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from datetime import datetime
from intouch_app.models import Contact, Note
from intouch_app.main.forms import ContactForm, NoteForm, DeleteForm

from intouch_app.extensions import db

main = Blueprint("main", __name__)


@main.route("/")
@login_required
def homepage():
    """Show homepage."""
    all_contacts = Contact.query.filter_by(user_id=current_user.id).all()
    return render_template("home.html", contacts=all_contacts)


@main.route("/create_contact", methods=["GET", "POST"])
@login_required
def create_contact():
    form = ContactForm()

    if form.validate_on_submit():
        new_contact = Contact(
            name=form.name.data,
            email=form.email.data,
            phone=form.phone.data,
            address=form.address.data,
            birthday=form.birthday.data,
            image_url = form.image_url.data,
            relationship=form.relationship.data,
            user_id=current_user.id,
        )
        db.session.add(new_contact)
        db.session.commit()

        flash("New contact was created successfully.")
        return redirect(url_for("main.contact_detail", contact_id=new_contact.id))
    return render_template("create_contact.html", form=form)


@main.route("/contact/<contact_id>", methods=["GET", "POST"])
@login_required
def contact_detail(contact_id):
    contact = Contact.query.get(contact_id)
    notes = Note.query.filter_by(contact_id=contact_id).all()

    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))

    form = ContactForm(obj=contact)

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        contact.name = form.name.data
        contact.email = form.email.data
        contact.phone = form.phone.data
        contact.address = form.address.data
        contact.birthday = form.birthday.data
        contact.image_url = form.image_url.data
        contact.relationship = form.relationship.data

        db.session.commit()

        flash("Contact was updated successfully.")
        return redirect(url_for("main.contact_detail", contact_id=contact_id))

    return render_template(
        "contact_detail.html", contact=contact, notes=notes, form=form
    )


@main.route("/contact/<contact_id>/edit", methods=["GET", "POST"])
@login_required
def edit_contact(contact_id):
    contact = Contact.query.get(contact_id)
    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))

    form = ContactForm(obj=contact)

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        contact.name = form.name.data
        contact.email = form.email.data
        contact.phone = form.phone.data
        contact.address = form.address.data
        contact.birthday = form.birthday.data
        contact.image_url = form.image_url.data
        contact.relationship = form.relationship.data

        db.session.commit()

        flash("Contact was updated successfully.")
        return redirect(url_for("main.contact_detail", contact_id=contact_id))

    return render_template("edit_contact.html", contact=contact, form=form)


@main.route("/contact/<contact_id>/delete", methods=["GET", "POST"])
@login_required
def delete_contact(contact_id):
    contact = Contact.query.get(contact_id)
    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))

    form = DeleteForm(obj=contact)

    if form.validate_on_submit():
        db.session.delete(contact)
        db.session.commit()

        flash("Contact was deleted successfully.")
        return redirect(url_for("main.homepage"))
    return render_template("delete_contact.html", contact=contact, form=form)


@main.route("/contact/<contact_id>/create_note", methods=["GET", "POST"])
@login_required
def create_note(contact_id):
    contact = Contact.query.get(contact_id)
    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))

    form = NoteForm()

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_note = Note(
            note=form.note.data, created_on=datetime.now(), contact_id=contact.id
        )

        db.session.add(new_note)
        db.session.commit()

        flash("New note was created successfully.")
        return redirect(url_for("main.contact_detail", contact_id=contact.id))

    return render_template("create_note.html", contact=contact, form=form)


@main.route("/contact/<contact_id>/note/<note_id>/edit", methods=["GET", "POST"])
@login_required
def edit_note(contact_id, note_id):
    contact = Contact.query.get(contact_id)
    note = Note.query.get(note_id)
    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))

    form = NoteForm(obj=note)

    # if form was submitted and contained no errors
    if form.validate_on_submit():
        note.note = form.note.data
        note.created_on = datetime.now()

        db.session.add(note)
        db.session.commit()

        flash("Note was updated successfully.")
        return redirect(url_for("main.contact_detail", contact_id=contact.id))

    return render_template(
        "edit_note.html", contact=contact, note=note, form=form
    )


@main.route("/contact/<contact_id>/note/<note_id>", methods=["GET", "POST"])
@login_required
def delete_note(contact_id, note_id):
    contact = Contact.query.get(contact_id)
    note = Note.query.get(note_id)
    if contact is None or contact.user_id != current_user.id:
        return redirect(url_for("main.homepage"))
    form = DeleteForm(obj=contact)
    if form.validate_on_submit():
        db.session.delete(note)
        db.session.commit()

        flash("Note was deleted successfully.")
        return redirect(url_for("main.contact_detail", contact_id=contact.id))
    return render_template("delete_note.html", contact=contact, note=note, form=form)

intouch_app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>InTouch</title>
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"> -->
    <link rel="stylesheet" href="/static/style.css">
</head>

<body>
    <!-- Add base html here. -->
    <header class="navbar">
        <h2><a href="/">InTouch</a></h2>
        <section class="flash-messages">
            {% for message in get_flashed_messages() %}
            <p>{{ message }}</p>
            {% endfor %}
        </section>
        <nav class="navbar-links">
            {% if current_user.is_authenticated %}
            <span class="hello">Hello {{ current_user.username }}</span>
            {% endif %}
            {% if current_user.is_authenticated %}
            <a href="/">Home</a>
            <a href="/create_contact">Add Contact</a>
            <a href="/logout">Log Out</a>
            {% else %}
            <a href="/signup">Sign Up</a>
            <a href="/login">Log In</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>

</html>

intouch_app/templates/contact_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="contact-detail">
    <section class="contact-detail-info">
        <header class="contact-detail-info-header">
            <h1>{{ contact.name }}</h1>
            <a href="/contact/{{ contact.id }}/edit" class="link-btn">Edit</a>
        </header>

        <section class="contact-detail-info-img">
            {% if contact.image_url %}
            <img src="{{ contact.image_url }}" alt="Contact image" />
            {% else %}
            <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcatking.in%2Fwp-content%2Fuploads%2F2017%2F02%2Fdefault-profile-1.png&f=1&nofb=1&ipt=e5059ecca894373e35ccdecfaeef2114b9074783a3569c2a93bc960646ff76ce&ipo=images"
                alt="Contact image" />
            {% endif %}
        </section>
        {%if contact.email %}
        <p>📧 {{ contact.email }}</p>
        {% endif %}
        {% if contact.phone %}
        <p>📞 {{ contact.phone }}</p>
        {% endif %}
        {% if contact.address %}
        <p>📫 {{ contact.address }}</p>
        {% endif %}
        {% if contact.birthday %}
        <p>
            🎂 {{ contact.birthday.strftime('%B %d') }}
            </p>
            {% endif %}
        {% if contact.relationship %}
        <p>🏷️ {{ contact.relationship }}</p>
        {% endif %}
        </section>

    <section class="contact-detail-notes">
        <header class="contact-detail-notes-header">
            <h1>Notes</h1>
            <a href="/contact/{{ contact.id }}/create_note" class="link-btn">Add Note</a>
        </header>

        {% if notes %}
        <ul class="note-list">
            {% for note in notes %}
            <li class="note">
                <section class="note-section">
                    <p>{{ note.created_on.strftime('%B %d, %Y') }}</p>
                    <a href="/contact/{{ contact.id }}/note/{{ note.id }}/edit" class="link-btn">Edit</a>
                </section>
                <p class="note-text">{{ note.note }}</p>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </section>
    <section class="contact-detail-timeline"></section>
    </section>

{% endblock %}

intouch_app/templates/create_contact.html
{% extends 'base.html' %}

{% block content %}
<section>
<form method="POST" action="{{ url_for('main.create_contact') }}">
    {{ form.csrf_token }}
    <fieldset class="fieldset-margin">
        <legend>Add a new contact</legend>

        <section class="form-section">

            {{ form.name.label }}
            {{ form.name }}
        </section>
        <ul>
            {% for error in form.name.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.email.label }}
            {{ form.email }}
        </section>
        <ul>
            {% for error in form.email.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.phone.label }}
            {{ form.phone }}
        </section>
        <ul>
            {% for error in form.phone.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.address.label }}
            {{ form.address }}
        </section>
        <ul>
            {% for error in form.address.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.birthday.label }}
            {{ form.birthday(placeholder="YYYY-mm-dd") }}
        </section>
        <ul>
            {% for error in form.birthday.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.relationship.label }}
            {{ form.relationship }}
        </section>
        <ul>
            {% for error in form.relationship.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        <section class="form-section">
            {{ form.image_url.label }}
            {{ form.image_url }}
        </section>
        <ul>
            {% for error in form.image_url.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>
        {{ form.submit }}
    </fieldset>
</form>
<footer>
    <a href="{{ url_for('main.homepage') }}" class="link-btn-black">Go Back</a>
</footer>
</section>
{% endblock %}

intouch_app/templates/create_note.html
{% extends 'base.html' %}

{% block content %}
<section>

    <form method="POST" action="{{ url_for('main.create_note', contact_id=contact.id) }}">
        {{ form.csrf_token }}
        <fieldset class="fieldset-margin">
            <legend>Add a note for {{ contact.name }} </legend>

            {{ form.note(class="form-control") }}
            <ul>
                {% for error in form.note.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.submit }}
        </fieldset>
    </form>
    <footer>
        <a href="{{ url_for('main.contact_detail', contact_id=contact.id) }}" class="link-btn-black">Back to {{
            contact.name
            }}</a>
    </footer>
</section>

{% endblock %}

intouch_app/templates/delete_contact.html
{% extends 'base.html' %}

{% block content %}
<section class="delete">
  <form method="POST" action="{{ url_for('main.delete_contact', contact_id=contact.id) }}">
    {{ form.csrf_token }}
    <fieldset class="fieldset-margin">
      <legend>Delete Contact</legend>
      <p>Are you sure you want to delete {{ contact.name }}? This can't be undone!</p>
      {{ form.submit }}
    </fieldset>
  </form>
  <footer>
    <a href="{{ url_for('main.edit_contact', contact_id=contact.id) }}" class="link-btn-black">Back to Edit</a>
  </footer>
</section>

{% endblock %}

intouch_app/templates/delete_note.html
{% extends 'base.html' %}

{% block content %}
<section class="delete">
  <form method="POST" action="{{ url_for('main.delete_note', contact_id=contact.id, note_id=note.id) }}">
    {{ form.csrf_token }}
    <fieldset class="fieldset-margin">
      <legend>Delete Note</legend>
      <p>Are you sure you want to delete {{ contact.name }}'s note? This can't be undone!</p>
      {{ form.submit }}
    </fieldset>
  </form>
  <footer>
    <a href="{{ url_for('main.edit_note', contact_id=contact.id, note_id=note.id) }}" class="link-btn-black">Back to
      Edit Note</a>
  </footer>
</section>

{% endblock %}

intouch_app/templates/edit_contact.html
{% extends 'base.html' %}

{% block content %}
<section>

    <form method="POST" action="{{ url_for('main.edit_contact', contact_id=contact.id) }}">
        {{ form.csrf_token }}
        <fieldset class="fieldset-margin">
            <legend>Edit contact</legend>
            <section class="form-section">
                {{ form.name.label }}
                {{ form.name }}
                </section>
                <ul>
                    {% for error in form.name.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
                <section class="form-section">
                    {{ form.email.label }}
                    {{ form.email }}
                </section>
                <ul>
                    {% for error in form.email.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
                <section class="form-section">
                    {{ form.phone.label }}
                    {{ form.phone }}
                </section>
                <ul>
                    {% for error in form.phone.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
                <section class="form-section">
                    {{ form.address.label }}
                    {{ form.address }}
                </section>
                <ul>
                    {% for error in form.address.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
                <section class="form-section">
                    {{ form.birthday.label }}
                    {{ form.birthday(placeholder="YYYY-mm-dd") }}
                </section>
                <ul>
                    {% for error in form.birthday.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
                <section class="form-section">
                    {{ form.relationship.label }}
                    {{ form.relationship }}
                </section>
                <ul>
                    {% for error in form.relationship.errors %}
                    <li class="error">{{ error }}</li>
                    {% endfor %}
                </ul>
            <section class="form-section">
                {{ form.image_url.label }}
                {{ form.image_url }}
            </section>
            <ul>
                {% for error in form.image_url.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            {{ form.submit }}
            </fieldset>
            </form>
    <footer>
        <a href="{{ url_for('main.contact_detail', contact_id=contact.id) }}" class="link-btn-black">Back to {{ contact.name
            }}</a>
        <a href="{{ url_for('main.delete_contact', contact_id=contact.id) }}" class="link-btn-black">Delete</a>
        <!-- <form method="POST" action="{{ url_for('main.delete_contact', contact_id=contact.id) }}">
                    {{ form.csrf_token }}
                    <p><input type="submit" name="btn" value="Delete"></p>
        </form> -->
        </footer>
        </section>

{% endblock %}

intouch_app/templates/edit_note.html
{% extends 'base.html' %}

{% block content %}
<section>

    <form method="POST" action="{{ url_for('main.edit_note', contact_id=contact.id, note_id=note.id) }}">
        {{ form.csrf_token }}
        <fieldset class="fieldset-margin">
            <legend>Edit note for {{ contact.name }}</legend>

            {{ form.note(class="form-control") }}
            <ul>
                {% for error in form.note.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.submit }}
        </fieldset>
    </form>
    <footer>
        <a href="{{ url_for('main.contact_detail', contact_id=contact.id) }}" class="link-btn-black">Back to {{
            contact.name
            }}</a>
        <a href="{{ url_for('main.delete_note', contact_id=contact.id, note_id=note.id) }}"
            class="link-btn-black">Delete Note</a>
    </footer>
</section>


{% endblock %}

intouch_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<section class="contact">
    <header>
        <p></p>
        <h1>Contacts</h1>
        <a href="/create_contact" class="link-btn-black">Add Contact</a>
    </header>
    <ul class="contact-list">
        {% for contact in contacts %}
        <a href="/contact/{{ contact.id }}">
            <li class="contact-card">
                {% if contact.image_url %}
                <img src="{{ contact.image_url }}" alt="Contact image" />
                {% else %}
                <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcatking.in%2Fwp-content%2Fuploads%2F2017%2F02%2Fdefault-profile-1.png&f=1&nofb=1&ipt=e5059ecca894373e35ccdecfaeef2114b9074783a3569c2a93bc960646ff76ce&ipo=images"
                    alt="Contact image" />
                {% endif %}
                <h3>{{ contact.name }}</h3>
            </li>
        </a>
        {% endfor %}
        </ul>
</section>

{% endblock %}

intouch_app/templates/login.html
{% extends 'base.html' %}
{% block content %}
<section class="auth">

    <h1>Log In</h1>

    <form action="/login" method="POST">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Enter your credentials</legend>
            <section class="form-section">
                {{ form.username.label }}
                {{ form.username }}
            </section>
            <ul>
                {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            <section class="form-section">
                {{ form.password.label }}
                {{ form.password }}
            </section>
            <ul>
                {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.submit }}
            </fieldset>
            </form>
</section>

{% endblock %}

intouch_app/templates/signup.html
{% extends 'base.html' %}
{% block content %}
<section class="auth">
    <h1>Sign Up</h1>

    <form action="/signup" method="POST">
        {{ form.csrf_token }}
        <fieldset>
            <legend>Enter your credentials</legend>
            <section class="form-section">
                {{ form.username.label }}
                {{ form.username }}
            </section>
            <ul>
                {% for error in form.username.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
            <section class="form-section">
                {{ form.password.label }}
                {{ form.password }}
            </section>
            <ul>
                {% for error in form.password.errors %}
                <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>

            {{ form.submit }}
        </fieldset>
        </form>
</section>
{% endblock %}